### ISSUE TITLE
GStreamer with C920

### ISSUE THREAD

**Issue by KevKo1990** [matthiasbock/gstreamer-phone#11]
Dear @matthiasbock,

I hope you are still active in this project. I read your issue on https://github.com/matthiasbock/gstreamer-phone/issues/1 and I face a now similar problem on the C920.

Neither your uvch264 nor v4l2src automatically adjusts the bitrate for different solution at leasr when I am testing.

Do you know if there is any update or automatic mode released to adjust the bitrate according to the resolution? Or is it something I have to code e.g. in a mapping table on my side?

Thank you in advance!

**Comment by matthiasbock** [comment]
Hi,
I don't understand. Can you explain with a little more detail?
What exactly did you do and what is the problem?

**Comment by KevKo1990** [comment]
Hi Matthias,
thanks for your reply - my problems solved, using uvch264 worked finally
